version: '3'

services:
  ## 서비스 이름
  redis:
    image: redis
    container_name: redis
    hostname: root
    ports:
      - "6379:6379"
    networks:
      - my_network

  dataportal_web:
    container_name: dataportal-web
    image: choco22/web
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - my_network

#  dataportal_datastore:
#    container_name: dataportal-dateStore
#    image: choco22/datastore
#    ports:
#      - "8081:8081"
#    depends_on:
#      - redis
#    networks:
#      - my_network

networks:
  my_network: