spring:

    datasource:
        url: jdbc:mysql://localhost:3306/hanyang?useSSL=true&characterEncoding=UTF-8
        username: root
        password: 8891
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL57Dialect
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                connection:
                    CharSet: utf8
                    useUnicode: true
                    characterEncoding: utf-8

        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true

server:
    port: 8080