name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradle set up
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: gradlew 권한 설정
        run: chmod +x gradlew

      - name: gateway-api application.yml 생성
        run: |
          cd ./gateway-api/src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_GATEWAY }}" > ./application-prod.yml
        shell: bash

      - name: data-crawler application.yml 생성
        run: |
          cd ./data-crawler/src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_CRAWLER }}" > ./application-prod.yml
        shell: bash

      - name: data-ingestor application.yml 생성
        run: |
          cd ./data-ingestor/src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_INGESTOR }}" > ./application-prod.yml
        shell: bash

      - name: 빌드 확인
        run: ./gradlew build

      - name: Docker set up
        uses: docker/setup-buildx-action@v3

      - name: Docker gateway-api 이미지 빌드
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gateway-api:latest ./gateway-api 
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway-api:latest

      - name: Docker data-crawler 이미지 빌드
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/data-crawler:latest ./data-crawler 
          docker push ${{ secrets.DOCKER_USERNAME }}/data-crawler:latest

      - name: Docker data-ingestor 이미지 빌드
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/data-ingestor:latest ./data-ingestor 
          docker push ${{ secrets.DOCKER_USERNAME }}/data-ingestor:latest

      - name: EC2 배포
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            # 기존 컨테이너 중지 및 제거
            docker-compose down || true
            
            # 이미지 업데이트
            docker pull ${{ secrets.DOCKER_USERNAME }}/gateway-api:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/data-crawler:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/data-ingestor:latest
            
            # 새 컨테이너 실행
            docker-compose up -d


